### ISSUE TITLE
React group project: set up your Kanban board

### ISSUE THREAD

**Issue by devendra-alt** [devendra-alt/space-travel-hub#26]
# [React group project: set up your Kanban board](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md)
✔️ Added project for space traveler hub
✔️ Assigned tasks to individual group member
✔️ We are **2 members** of this group project

### link to our project ▶️  https://github.com/devendra-alt/space-travel-hub/projects/1

**Comment by DammyShittu** [comment]
Hi @devendra-alt and @kkmanuu,

## Highlights
✔️ Assigning of tasks

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly ensure all your group tasks are assigned. You can assign them to multiple members.

  ![image](https://github.com/devendra-alt/space-travel-hub/assets/54848363/8c791e58-e36f-4bef-9fb9-18bbf09ffd39)

- [ ] You should have 17 tasks, but you have only 16. You are missing this task. Kindly add it.

  ![image](https://github.com/devendra-alt/space-travel-hub/assets/54848363/3761b4af-0dbb-430b-b918-73c55a6e26c3)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by devendra-alt** [comment]
thank you @DammyShittu, your feedback is valuable 💯

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
